### ISSUE TITLE
detecting changes when using non-js includes crashes

### ISSUE THREAD

**Issue by peacememories** [sca-/webpack-watch-time-plugin#5]
In our build process we use scss via `sass-loader`. In scss imports do not contain the `.scss` extension, so for example an import for `about.scss` would look like this:
```
@import "about";
```

When using this plugin with `detect: true` it crashes when trying to read an "about" file at
https://github.com/sca-/webpack-watch-time-plugin/blob/400e16410fab9b689d27a20915f78317626e0a65/index.js#L10
because apparently the `watching.fileDependencies` are not resolved before being passed to the plugin.

Excerpt from `sourceFiles` at
https://github.com/sca-/webpack-watch-time-plugin/blob/400e16410fab9b689d27a20915f78317626e0a65/index.js#L88

```
<path to application redacted>/style/_won-config.scss
<path to application redacted>/style/won.scss
about
accordion
animate
```

**Comment by sca-** [comment]
Excuse me, I can not reproduce this issue.
What versions of `webpack` and `sass-loader` are you using precisely? 
And what does your `webpack.config` look like?

**Comment by peacememories** [comment]
Ironically, after reverting the changes and working on some other parts of the application for a bit I can't reproduce it exactly, either.
The problem still seems to be there, though it doesn't crash anymore and instead reports "Cannot get source of ..." for all of our scss modules.
It could be to do with the fact we're using a non-default importer for scss (because of circular imports).

The webpack config in question is here:
https://github.com/researchstudio-sat/webofneeds/blob/8f5ed5ee8b8e8cdac305c8fb1c119530db065a89/webofneeds/won-owner-webapp/src/main/webapp/webpack.config.ts

**Comment by peacememories** [comment]
Interestingly it still seems to be able to detect wether changes in the scss files were made ^^'

**Comment by sca-** [comment]
I've taken a look at this `node-sass-import-once` module code. Seems like it permits some invalid (from webpack & SASS point of view) import syntax while fixing paths inside the Importer itself.

For example, it does permit this code:
```@import "file";```
when only `./_file.sass` path exists.

So it's kind of this particular Sass Importer module internal magic 🙂 

Nevertheless, **webpack does resolve** this imports eventually (when the real paths are already returned by Sass Importer module), so both of paths `"file"` and `"/path/to/real/_file.sass"` are present in `watching.fileDependencies`. So this currupted filepath is excess but not necessary for our goals after all.

That's why for this issue I've made up with a new feature: `logLevels` config. Check it out!
```npm i -D webpack-watch-time-plugin@0.3```
It doesn't fix anything regarding the issue itself (because it doesn't really seem like a bug after all — just a custom Sass Importer module side-effect), but it hides this unnecessary log info/warn messages  behind a config node (set to `logLevel: 'error'` by default)

Please write me if this solution satisfies your needs.
Regards, Evgeniy

**Comment by peacememories** [comment]
In fact this is way more than I expected, thanks for helping so quickly and taking the time to look into our import module. I'm fairly new to the project and didn't know that the import syntax we were using was illegal. Another point to add to our technical debt list I guess^^

Thanks again for the quick help and the convenient plugin :)
